version: '3.8'
services:
  web-app:
    image: pixelplanet5/filamentdb-app:latest
    ports:
      - "3000:3000"
    volumes:
      - ./public/downloads:/app/public/downloads
      - ./data:/app/data
    restart: unless-stopped
