version: '3.8'
services:
  web-app:
    build: .
    image: pixelplanet5/filamentdb-app:latest
    ports:
      - "3000:3000"
    volumes:
      - ./public/downloads:/app/public/downloads
      - ./data:/app/data
    environment:
      - SYNC_API_KEY=test
      - ENABLE_USER_MANAGEMENT=true
      - AUTH_SECRET=dev-secret-change-me
    restart: unless-stopped
